language: python

python:
 - "3.6"
 - "3.5"
 - "2.7"

sudo: false

install:
 - pip install pycodestyle pyflakes tox-travis

script:
 # Tests
 - tox

after_script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
